# docker-compose.yml

services:
  app:
    build: .
    ports:
      - "9998:9998"
    environment:
      SPRING_DATASOURCE_URL:   jdbc:mariadb://db:3306/company
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
      SPRING_MAIL_HOST:         smtp.gmail.com
      SPRING_MAIL_PORT:         587
      SPRING_MAIL_USERNAME:     nguyenbaminhtriet0947@gmail.com
      SPRING_MAIL_PASSWORD:     your_app_password
    depends_on:
      - db

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD:    123456789
      MARIADB_DATABASE:         company
    ports:
      - "3307:3306"

  jenkins:
    build:
      context: ./jenkins
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

# Định nghĩa volume
volumes:
  jenkins_home:
